stages:
  - build

cache:
  paths:
    - .m2/repository  # For Java Maven dependencies
    - venv/  # For Python virtual environment, if using one

# Job for building Java project in subdirectory1
build_access_dataserver:
  image: 842030182425.dkr.ecr.us-east-1.amazonaws.com/privacera_build_jdk17:main-1.0.0.1-SNAPSHOT-latest
  tags:
    - privacera-jdk
  stage: build
  script:
    - cd access/dataserver
    - mvn clean install
  only:
    changes:
      - access/dataserver/**/*


# Job for building Python project in subdirectory3
#build_subdirectory3:
#  stage: build
#  script:
#    - cd subdirectory3
#    - python -m venv venv
#    - source venv/bin/activate
#    - pip install -r requirements.txt
#  only:
#    changes:
#      - subdirectory3/**/*
